### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by serhathan** [ssav7912/GDALforUE5#1]
Hello, I attempted to utilize this plugin because I wanted to avoid dealing with Conan-UE4, UE4 CLI, or downloading UE source from GitHub. However, it seems that I am encountering difficulties in building this plugin as well. I did not find CMake for Glad inside the plugin.

**Comment by ssav7912** [comment]
Hi, I do have a release distribution in the 'Releases' section of the project, give that a try.

Otherwise, you need to build GDAL from source as detailed in the GDAL documentation here: [https://gdal.org/development/building_from_source.html](https://gdal.org/development/building_from_source.html). Alternatively, you can source prebuilt GDAL binaries from the OSGEO4W package manager. You can then copy the binaries into the location described in this plugin's README.
